(part "AFS14A04-1575_42-T3"
    (packageRef "AFS14A04157542T3")
    (interface
        (port "A1" (symbPinId 1) (portName "OUTPUT") (portType INOUT))
        (port "B1" (symbPinId 2) (portName "GROUND_1") (portType INOUT))
        (port "C1" (symbPinId 3) (portName "INPUT") (portType INOUT))
        (port "D1" (symbPinId 4) (portName "GROUND_2") (portType INOUT))
        (port "E1" (symbPinId 5) (portName "GROUND_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "155")
    (property "Mouser_Part_Number" "815-AFS14A04-1575-T3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ABRACON/AFS14A04-1575.42-T3?qs=tfZGHB2PWd3aRd4qy%2Fp2mg%3D%3D")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "AFS14A04-1575.42-T3")
    (property "Description" "Signal Conditioning 1575.42MHz BW=40MHz 5-Pad")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/dk/DKDS-11/202926.pdf")
    (property "symbolName1" "AFS14A04-1575_42-T3")
)
